// src/screens/admisiones/Admisiones.tsx
import { useEffect, useState } from 'react'
import { FichaAdmisionModal } from '../../reports/fichaAdmision/FichaAdmision'
import { SisFuaReport } from '../../reports/sisFua/SisFuaReport'
import { buscarPendientesAdmision, cargarCatalogos } from './api'
import { DetallePacienteModal } from './DetallePacienteModal'
import type { CatalogoItem, PendienteAdmision } from './types'
import { formatFechaTriaje, tipoPrioridadInfo } from './types'

export function Admisiones() {
  const [fecha, setFecha] = useState(new Date().toISOString().slice(0, 10))
  const [filtro, setFiltro] = useState('')
  const [idDepartamento, setIdDepartamento] = useState('0')
  const [idEspecialidad, setIdEspecialidad] = useState('0')
  const [idServicio, setIdServicio] = useState('0')
  const [departamentos, setDepartamentos] = useState<CatalogoItem[]>([])
  const [especialidades, setEspecialidades] = useState<CatalogoItem[]>([])
  const [servicios, setServicios] = useState<CatalogoItem[]>([])

  const [items, setItems] = useState<PendienteAdmision[]>([])
  const [cargando, setCargando] = useState(false)
  const [error, setError] = useState('')
  const [buscar, setBuscar] = useState(false)
  const [pacienteAdmision, setPacienteAdmision] = useState<PendienteAdmision | null>(null)
  const [fichaCuenta, setFichaCuenta] = useState<number | null>(null)
  const [fuaCuenta, setFuaCuenta] = useState<number | null>(null)
  const [mensajeExito, setMensajeExito] = useState('')

  function handleAdmisionExitosa(mensaje: string) {
    setPacienteAdmision(null)
    setMensajeExito(mensaje)
    handleBuscar()
  }

  useEffect(() => {
    let cancelled = false
    cargarCatalogos().then(({ departamentos: d, especialidades: e, servicios: s }) => {
      if (cancelled) return
      setDepartamentos(d)
      setEspecialidades(e)
      setServicios(s)
    })
    return () => { cancelled = true }
  }, [])

  async function handleBuscar() {
    setCargando(true)
    setError('')
    setItems([])
    try {
      const result = await buscarPendientesAdmision({ fecha, idDepartamento, idEspecialidad, idServicio, filtro })
      setItems(result)
      setBuscar(true)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Error de conexión.')
    } finally {
      setCargando(false)
    }
  }

  return (
    <div className="gp-in" style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
      <div>
        <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '.14em', color: '#7a86a1', textTransform: 'uppercase' }}>Bandeja de admisión</div>
        <h1 style={{ margin: '4px 0 6px', fontSize: 24, fontWeight: 700, color: '#07153a' }}>Pacientes post-triaje sin admisión</h1>
        <p style={{ margin: 0, fontSize: 13, color: '#7a86a1', maxWidth: 640, lineHeight: 1.5 }}>
          Listado de pacientes ya triados que aún no tienen admisión registrada. Filtre por fecha, paciente,
          departamento, especialidad o consultorio para localizar la bandeja.
        </p>
      </div>

      <div style={{ background: '#fff', border: '1px solid #e6eaf2', borderRadius: 16, padding: '18px 20px' }}>
        <div style={{ display: 'grid', gridTemplateColumns: '150px 1fr 1fr 1fr 1fr auto', gap: 10, alignItems: 'end' }}>
          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#54617f', marginBottom: 6 }}>Fecha</label>
            <input type="date" value={fecha} onChange={e => setFecha(e.target.value)} style={{ width: '100%', padding: '9px 12px', border: '1px solid #e0e6f1', borderRadius: 11, fontSize: 13.5, background: '#f8fafc', color: '#07153a' }} />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#54617f', marginBottom: 6 }}>Paciente</label>
            <input
              value={filtro}
              onChange={e => setFiltro(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter') handleBuscar() }}
              placeholder="Buscar por nombre o documento..."
              style={{ width: '100%', padding: '10px 14px', border: '1px solid #e0e6f1', borderRadius: 11, fontSize: 13.5, background: '#f8fafc', color: '#07153a' }}
            />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#54617f', marginBottom: 6 }}>Departamento</label>
            <select value={idDepartamento} onChange={e => setIdDepartamento(e.target.value)} style={{ width: '100%', padding: '10px 12px', border: '1px solid #e0e6f1', borderRadius: 11, fontSize: 13.5, background: '#f8fafc', color: '#07153a' }}>
              <option value="0">Todos</option>
              {departamentos.map(d => <option key={d.id} value={d.id}>{d.nombre}</option>)}
            </select>
          </div>

          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#54617f', marginBottom: 6 }}>Especialidad</label>
            <select value={idEspecialidad} onChange={e => setIdEspecialidad(e.target.value)} style={{ width: '100%', padding: '10px 12px', border: '1px solid #e0e6f1', borderRadius: 11, fontSize: 13.5, background: '#f8fafc', color: '#07153a' }}>
              <option value="0">Todas</option>
              {especialidades.map(s => <option key={s.id} value={s.id}>{s.nombre}</option>)}
            </select>
          </div>

          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#54617f', marginBottom: 6 }}>Consultorio</label>
            <select value={idServicio} onChange={e => setIdServicio(e.target.value)} style={{ width: '100%', padding: '10px 12px', border: '1px solid #e0e6f1', borderRadius: 11, fontSize: 13.5, background: '#f8fafc', color: '#07153a' }}>
              <option value="0">Todos</option>
              {servicios.map(s => <option key={s.id} value={s.id}>{s.nombre}</option>)}
            </select>
          </div>

          <button
            onClick={handleBuscar}
            disabled={cargando}
            className="gp-primary-btn"
            style={{ display: 'flex', alignItems: 'center', gap: 7, height: 42, padding: '0 20px', background: '#263c7a', color: '#fff', border: 'none', borderRadius: 11, fontSize: 14, fontWeight: 600, cursor: cargando ? 'wait' : 'pointer', whiteSpace: 'nowrap' }}
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4"><circle cx="11" cy="11" r="7" /><path d="M21 21l-4.3-4.3" /></svg>
            Buscar
          </button>
        </div>
      </div>

      {error && (
        <div style={{ background: '#fee2e2', border: '1px solid #fca5a5', color: '#b91c1c', fontSize: 13, fontWeight: 500, padding: '10px 13px', borderRadius: 11 }}>
          {error}
        </div>
      )}

      {mensajeExito && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '13px 16px', borderRadius: 13, background: '#ecfdf5', border: '1px solid #a7f3d0', color: '#047857', fontSize: 13.5, fontWeight: 600 }}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" style={{ flexShrink: 0 }}><circle cx="12" cy="12" r="10" /><path d="M8 12.5l2.5 2.5L16 9.5" /></svg>
          {mensajeExito}
          <button onClick={() => setMensajeExito('')} style={{ marginLeft: 'auto', background: 'none', border: 'none', color: '#047857', fontSize: 15, cursor: 'pointer', lineHeight: 1 }} aria-label="Cerrar">×</button>
        </div>
      )}

      <div style={{ background: '#fff', border: '1px solid #e6eaf2', borderRadius: 16, padding: '18px 20px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, marginBottom: 16, flexWrap: 'wrap' }}>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
            <span style={{ fontSize: 15, fontWeight: 700, color: '#07153a' }}>Resultados</span>
            <span style={{ fontSize: 12.5, color: '#7a86a1' }}>
              {buscar ? `${items.length} paciente(s) sin admisión` : 'Complete los filtros y pulse Buscar.'}
            </span>
          </div>
        </div>

        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ textAlign: 'left', color: '#7a86a1', fontWeight: 600, fontSize: 11.5, textTransform: 'uppercase', letterSpacing: '.03em' }}>
                <th style={{ padding: '0 10px 10px' }}>Prioridad</th>
                <th style={{ padding: '0 10px 10px' }}>Paciente</th>
                <th style={{ padding: '0 10px 10px' }}>Servicio</th>
                <th style={{ padding: '0 10px 10px' }}>Tipo ingreso</th>
                <th style={{ padding: '0 10px 10px' }}>Fecha triaje</th>
                <th style={{ padding: '0 10px 10px' }}>IAFA</th>
                <th style={{ padding: '0 10px 10px', textAlign: 'right' }}>Acción</th>
              </tr>
            </thead>
            <tbody>
              {items.length === 0 ? (
                <tr><td colSpan={7} style={{ padding: '20px 10px', color: '#94a0bd', textAlign: 'center' }}>
                  {cargando ? 'Consultando...' : buscar ? 'No se encontraron pacientes para los filtros aplicados.' : 'Realice una búsqueda para ver resultados.'}
                </td></tr>
              ) : (
                items.map(p => {
                  const prio = p.IdTipoPrioridad != null ? tipoPrioridadInfo[p.IdTipoPrioridad] : undefined
                  return (
                    <tr key={p.idTriaje} className="gp-row" style={{ borderTop: '1px solid #eef1f6' }}>
                      <td style={{ padding: '12px 10px', verticalAlign: 'top' }}>
                        {prio ? (
                          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 7, padding: '5px 12px', borderRadius: 999, background: prio.bg, color: prio.text, fontSize: 12, fontWeight: 700, whiteSpace: 'nowrap' }}>
                            <span style={{ width: 7, height: 7, borderRadius: '50%', background: prio.dot, flexShrink: 0 }} />
                            {prio.label}
                          </span>
                        ) : (
                          <span style={{ fontSize: 12, color: '#7a86a1' }}>{p.prioridad ?? '—'}</span>
                        )}
                      </td>
                      <td style={{ padding: '12px 10px', verticalAlign: 'top' }}>
                        <div style={{ fontWeight: 600, color: '#07153a' }}>{p.Paciente || 'Paciente NN'}</div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 3, flexWrap: 'wrap' }}>
                          <span style={{ fontSize: 12, color: '#54617f' }}>{`DNI: ${p.NroDocumento ?? '—'}`}</span>
                          {p.IdCuentaAtencion != null && (
                            <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, padding: '3px 9px', borderRadius: 999, background: '#d1fae5', color: '#047857', fontSize: 11, fontWeight: 700, whiteSpace: 'nowrap' }}>
                              <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><polyline points="20 6 9 17 4 12" /></svg>
                              {p.IdCuentaAtencion}
                            </span>
                          )}
                        </div>
                      </td>
                      <td style={{ padding: '12px 10px', verticalAlign: 'top', color: '#54617f', maxWidth: 200 }}>{p.Servicio ?? '—'}</td>
                      <td style={{ padding: '12px 10px', verticalAlign: 'top', color: '#54617f' }}>{p.TipoIngreso ?? '—'}</td>
                      <td style={{ padding: '12px 10px', verticalAlign: 'top', color: '#54617f' }}>{formatFechaTriaje(p.fecha_Triaje)}</td>
                      <td style={{ padding: '12px 10px', verticalAlign: 'top' }}>
                        <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '4px 10px', borderRadius: 999, background: '#e0f2fe', color: '#075985', fontSize: 11.5, fontWeight: 700, whiteSpace: 'nowrap' }}>
                          {p.IAFA || '—'}
                        </span>
                      </td>
                      <td style={{ padding: '12px 10px', verticalAlign: 'top', textAlign: 'right' }}>
                        {p.IdCuentaAtencion != null ? (
                          <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
                            <button
                              onClick={() => setFichaCuenta(p.IdCuentaAtencion)}
                              className="gp-primary-btn"
                              style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '7px 14px', background: '#263c7a', color: '#fff', border: 'none', borderRadius: 9, fontSize: 12, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap' }}
                            >
                              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><path d="M14 2v6h6" /><path d="M16 13H8M16 17H8M10 9H8" /></svg>
                              Ficha admisión
                            </button>
                            {p.IAFA?.toUpperCase().includes('SIS') && (
                              <button
                                onClick={() => setFuaCuenta(p.IdCuentaAtencion)}
                                className="gp-primary-btn"
                                style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '7px 14px', background: '#075985', color: '#fff', border: 'none', borderRadius: 9, fontSize: 12, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap' }}
                              >
                                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><path d="M6 9V2h12v7" /><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" /><rect x="6" y="14" width="12" height="8" /></svg>
                                FUA
                              </button>
                            )}
                          </div>
                        ) : (
                          <button
                            onClick={() => setPacienteAdmision(p)}
                            className="gp-primary-btn"
                            style={{ display: 'inline-flex', alignItems: 'center', gap: 7, padding: '8px 16px', background: '#263c7a', color: '#fff', border: 'none', borderRadius: 10, fontSize: 12.5, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap' }}
                          >
                            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.6"><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
                            Para admisionar
                          </button>
                        )}
                      </td>
                    </tr>
                  )
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {pacienteAdmision && (
        <DetallePacienteModal
          paciente={pacienteAdmision}
          onClose={() => setPacienteAdmision(null)}
          onSuccess={handleAdmisionExitosa}
        />
      )}

      {fichaCuenta != null && (
        <FichaAdmisionModal
          idCuentaAtencion={fichaCuenta}
          onClose={() => setFichaCuenta(null)}
        />
      )}

      {fuaCuenta != null && (
        <SisFuaReport
          idCuentaAtencion={fuaCuenta}
          onClose={() => setFuaCuenta(null)}
        />
      )}
    </div>
  )
}

// src/app/modulos/admisiones/adaptadores/entrada/ui/paginas/admisiones.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { MaestrosApiService } from '../../../../../../compartido/api/maestros.api.service';
import { AuthService } from '../../../../../auth/aplicacion/auth.service';

interface CatalogoItem {
  id: number;
  nombre: string;
}

@Component({
  selector: 'app-admisiones',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './admisiones.component.html'
})
export class AdmisionesComponent implements OnInit {
  private readonly maestrosApi = inject(MaestrosApiService);
  public readonly authService = inject(AuthService);

  fecha = new Date().toISOString().slice(0, 10);
  filtro = '';
  idDepartamento = '0';
  idEspecialidad = '0';
  idServicio = '0';

  departamentos: CatalogoItem[] = [];
  especialidades: CatalogoItem[] = [];
  servicios: CatalogoItem[] = [];

  items: unknown[] = [];
  cargando = false;
  error = '';
  buscar = false;
  mensajeExito = '';

  ngOnInit() {
    this.cargarCatalogos();
  }

  async cargarCatalogos() {
    try {
      const [d, e, s] = await Promise.all([
        this.maestrosApi.getDepartamentos(),
        this.maestrosApi.getEspecialidades(),
        this.maestrosApi.getServicios(2)
      ]);

      if (Array.isArray(d)) this.departamentos = d;
      if (Array.isArray(e)) this.especialidades = e;
      if (Array.isArray(s)) this.servicios = s;
    } catch (error) {
      console.error('Error cargando catálogos:', error);
    }
  }

  async handleBuscar() {
    this.cargando = true;
    this.error = '';
    this.items = [];
    this.mensajeExito = '';
    setTimeout(() => {
      this.cargando = false;
      this.buscar = true;
    }, 500);
  }
}

<div class="gp-in" style="display: flex; flex-direction: column; gap: 18px;">


  <div style="background: #fff; border: 1px solid #e6eaf2; border-radius: 16px; padding: 18px 20px;">
    <div style="display: grid; grid-template-columns: 150px 1fr 1fr 1fr 1fr auto; gap: 10px; align-items: end;">
      <div>
        <label for="fecha" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Fecha</label>
        <input id="fecha" type="date" [(ngModel)]="fecha" style="width: 100%; padding: 9px 12px; border: 1px solid #e0e6f1; border-radius: 11px; font-size: 13.5px; background: #f8fafc; color: #07153a;" />
      </div>
      <div>
        <label for="paciente" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Paciente</label>
        <input id="paciente" [(ngModel)]="filtro" (keydown.enter)="handleBuscar()" placeholder="Buscar por nombre o documento..."
               style="width: 100%; padding: 10px 14px; border: 1px solid #e0e6f1; border-radius: 11px; font-size: 13.5px; background: #f8fafc; color: #07153a;" />
      </div>
      <div>
        <label for="departamento" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Departamento</label>
        <select id="departamento" [(ngModel)]="idDepartamento" style="width: 100%; padding: 10px 12px; border: 1px solid #e0e6f1; border-radius: 11px; font-size: 13.5px; background: #f8fafc; color: #07153a;">
          <option value="0">Todos</option>
          @for (d of departamentos; track d.id) {
            <option [value]="d.id">{{ d.nombre }}</option>
          }
        </select>
      </div>
      <div>
        <label for="selEsp" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Especialidad</label>
        <select id="selEsp" [(ngModel)]="idEspecialidad" style="width: 100%; padding: 10px 12px; border: 1px solid #e0e6f1; border-radius: 11px; font-size: 13.5px; background: #f8fafc; color: #07153a;">
          <option value="0">Todas</option>
          @for (e of especialidades; track e.id) {
            <option [value]="e.id">{{ e.nombre }}</option>
          }
        </select>
      </div>
      <div>
        <label for="selServ" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Consultorio</label>
        <select id="selServ" [(ngModel)]="idServicio" style="width: 100%; padding: 10px 12px; border: 1px solid #e0e6f1; border-radius: 11px; font-size: 13.5px; background: #f8fafc; color: #07153a;">
          <option value="0">Todos</option>
          @for (s of servicios; track s.id) {
            <option [value]="s.id">{{ s.nombre }}</option>
          }
        </select>
      </div>
      <button type="button" (click)="handleBuscar()" [disabled]="cargando"
              style="display: flex; align-items: center; gap: 7px; height: 42px; padding: 0 20px; background: #263c7a; color: #fff; border: none; border-radius: 11px; font-size: 14px; font-weight: 600; cursor: pointer; white-space: nowrap;">
        <svg aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><circle cx="11" cy="11" r="7" /><path d="M21 21l-4.3-4.3" /></svg>
        Buscar
      </button>
    </div>
  </div>

  @if (error) {
    <div style="background: #fee2e2; border: 1px solid #fca5a5; color: #b91c1c; font-size: 13px; font-weight: 500; padding: 10px 13px; border-radius: 11px;">
      {{ error }}
    </div>
  }

  @if (mensajeExito) {
    <div style="display: flex; align-items: center; gap: 10px; padding: 13px 16px; border-radius: 13px; background: #ecfdf5; border: 1px solid #a7f3d0; color: #047857; font-size: 13.5px; font-weight: 600;">
      <svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" style="flex-shrink: 0;"><circle cx="12" cy="12" r="10" /><path d="M8 12.5l2.5 2.5L16 9.5" /></svg>
      {{ mensajeExito }}
      <button type="button" (click)="cerrarExito()" style="margin-left: auto; background: none; border: none; color: #047857; font-size: 15px; cursor: pointer; line-height: 1;" aria-label="Cerrar">×</button>
    </div>
  }

  <div style="background: #fff; border: 1px solid #e6eaf2; border-radius: 16px; padding: 18px 20px;">
    <div style="display: flex; align-items: center; justify-content: space-between; gap: 16px; margin-bottom: 16px; flex-wrap: wrap;">
      <div style="display: flex; align-items: baseline; gap: 8px;">
        <span style="font-size: 15px; font-weight: 700; color: #07153a;">Resultados</span>
        <span style="font-size: 12.5px; color: #7a86a1;">
          {{ buscar ? items.length + ' paciente(s) sin admisión' : 'Complete los filtros y pulse Buscar.' }}
        </span>
      </div>
    </div>

    <div style="overflow-x: auto;">
      <app-tabla [columnas]="columnasTabla" [datos]="items" [cargando]="cargando" mensajeCargando="Consultando..."
                 [mostrarFiltroRequerido]="!buscar" mensajeFiltroRequerido="Realice una búsqueda para ver resultados."
                 mensajeVacio="No se encontraron pacientes para los filtros aplicados.">

        <ng-template appColumnaTemplate="prioridadCustom" let-p>
          @if (prioridadInfo(p)) {
            <span style="display: inline-flex; align-items: center; gap: 7px; padding: 5px 12px; border-radius: 999px; font-size: 12px; font-weight: 700; white-space: nowrap;"
                  [style.background]="prioridadInfo(p)!.bg" [style.color]="prioridadInfo(p)!.text">
              <span [style.width]="'7px'" [style.height]="'7px'" style="border-radius: 50%; flex-shrink: 0;"
                    [style.background]="prioridadInfo(p)!.dot"></span>
              {{ prioridadInfo(p)!.label }}
            </span>
          } @else {
            <span style="font-size: 12px; color: #7a86a1;">{{ prioridadTexto(p) || '—' }}</span>
          }
        </ng-template>

        <ng-template appColumnaTemplate="pacienteCustom" let-p>
          <div style="font-weight: 600; color: #07153a;">{{ nombrePaciente(p) }}</div>
          <div style="display: flex; align-items: center; gap: 8px; margin-top: 3px; flex-wrap: wrap;">
            <span style="font-size: 12px; color: #54617f;">DNI: {{ documento(p) || '—' }}</span>
            @if (idCuentaAtencion(p) > 0) {
              <span style="display: inline-flex; align-items: center; gap: 5px; padding: 3px 9px; border-radius: 999px; background: #d1fae5; color: #047857; font-size: 11px; font-weight: 700; white-space: nowrap;">
                <svg aria-hidden="true" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><polyline points="20 6 9 17 4 12" /></svg>
                {{ idCuentaAtencion(p) }}
              </span>
            }
          </div>
        </ng-template>

        <ng-template appColumnaTemplate="servicioCustom" let-p>
          <span style="color: #54617f; display: block; max-width: 200px;">{{ servicio(p) || '—' }}</span>
        </ng-template>

        <ng-template appColumnaTemplate="tipoIngresoCustom" let-p>
          <span style="color: #54617f;">{{ tipoIngreso(p) || '—' }}</span>
        </ng-template>

        <ng-template appColumnaTemplate="fechaTriajeCustom" let-p>
          <span style="color: #54617f;">{{ formatFechaTriaje(p) }}</span>
        </ng-template>

        <ng-template appColumnaTemplate="iafaCustom" let-p>
          <span style="display: inline-flex; align-items: center; gap: 6px; padding: 4px 10px; border-radius: 999px; background: #e0f2fe; color: #075985; font-size: 11.5px; font-weight: 700; white-space: nowrap;">
            {{ iafa(p) || '—' }}
          </span>
        </ng-template>

        <ng-template appColumnaTemplate="sexoCustom" let-p>
          @if (sexo(p) === '1' || sexo(p)?.toUpperCase() === 'MASCULINO' || sexo(p)?.toUpperCase() === 'VARÓN' || sexo(p)?.toUpperCase() === 'VARON' || sexo(p)?.toUpperCase() === 'M' || sexo(p)?.toUpperCase() === 'V') {
            <svg aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#2563eb" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" title="Varón" style="margin: 0 auto;"><circle cx="10" cy="14" r="5"></circle><path d="M13.5 10.5 21 3"></path><path d="M16 3h5v5"></path></svg>
          } @else if (sexo(p) === '2' || sexo(p)?.toUpperCase() === 'FEMENINO' || sexo(p)?.toUpperCase() === 'MUJER' || sexo(p)?.toUpperCase() === 'F') {
            <svg aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#ec4899" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" title="Mujer" style="margin: 0 auto;"><circle cx="12" cy="10" r="5"></circle><path d="M12 15v7"></path><path d="M9 19h6"></path></svg>
          } @else {
            <span style="color: #94a0bd; font-weight: bold; font-size: 16px;">—</span>
          }
        </ng-template>

        <ng-template appColumnaTemplate="accionCustom" let-p>
          @if (idCuentaAtencion(p) > 0) {
            <div style="display: flex; gap: 8px; justify-content: flex-end;">
              <button type="button" (click)="abrirFicha(p)"
                      style="display: inline-flex; align-items: center; gap: 6px; padding: 7px 14px; background: #263c7a; color: #fff; border: none; border-radius: 9px; font-size: 12px; font-weight: 600; cursor: pointer; white-space: nowrap;">
                <svg aria-hidden="true" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><path d="M14 2v6h6" /><path d="M16 13H8M16 17H8M10 9H8" /></svg>
                Ficha admisión
              </button>
              @if (esSis(p)) {
                <button type="button" (click)="abrirFua(p)"
                        style="display: inline-flex; align-items: center; gap: 6px; padding: 7px 14px; background: #075985; color: #fff; border: none; border-radius: 9px; font-size: 12px; font-weight: 600; cursor: pointer; white-space: nowrap;">
                  <svg aria-hidden="true" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><path d="M6 9V2h12v7" /><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" /><rect x="6" y="14" width="12" height="8" /></svg>
                  FUA
                </button>
              }
            </div>
          } @else {
            <button type="button" (click)="abrirModalAdmision(p)"
                    style="display: inline-flex; align-items: center; gap: 7px; padding: 8px 16px; background: #263c7a; color: #fff; border: none; border-radius: 10px; font-size: 12.5px; font-weight: 600; cursor: pointer; white-space: nowrap;">
              <svg aria-hidden="true" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6"><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
              Para admisionar
            </button>
          }
        </ng-template>

      </app-tabla>
    </div>
  </div>

  @if (modalAdmision) {
    <ventana-modal [titulo]="nombrePaciente(modalAdmision)" subtitulo="Registrar admisión desde el triaje" [ancho]="560" (alCerrar)="cerrarModalAdmision()">
      <div style="margin-bottom: 18px; padding: 14px; border-radius: 12px; background: #f0f4ff; border: 1px solid #dbe3f4;">
        <div style="font-size: 18px; font-weight: 700; color: #07153a; text-transform: uppercase; letter-spacing: .01em;">{{ nombrePaciente(modalAdmision) }}</div>
        @if (documento(modalAdmision)) {
          <div style="font-size: 12.5px; color: #7a86a1; margin-top: 4px;">Documento: {{ documento(modalAdmision) }}</div>
        }
      </div>

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 14px;">
        <div>
          <label for="inNomAc" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Nombre del acompañante *</label>
          <input id="inNomAc" [(ngModel)]="formAdmision.nombreAcompanante" name="nombreAc" #nomAcCtrl="ngModel" required minlength="3" maxlength="120" autocomplete="off" placeholder="Ej: María Pérez"
                 style="width: 100%; padding: 10px 14px; border: 1px solid #d5dceb; border-radius: 11px; font-size: 14px; background: #f8fafc; color: #07153a;" />
          <app-error-mensaje [control]="nomAcCtrl"></app-error-mensaje>
        </div>
        <div>
          <label for="inTelAc" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Teléfono del acompañante *</label>
          <input id="inTelAc" [(ngModel)]="formAdmision.telefonoAcompanante" name="telAc" #telAcCtrl="ngModel" required pattern="^[0-9]{9}$" (keydown)="soloDigitos($event)" maxlength="15" autocomplete="off" placeholder="Ej: 987654321"
                 style="width: 100%; padding: 10px 14px; border: 1px solid #d5dceb; border-radius: 11px; font-size: 14px; background: #f8fafc; color: #07153a;" />
          <app-error-mensaje [control]="telAcCtrl"></app-error-mensaje>
        </div>
      </div>

      <div style="margin-top: 14px;">
        <label for="direccion-del-paciente" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Dirección del paciente *</label>
        <input id="direccion-del-paciente" [(ngModel)]="formAdmision.direccionPaciente" name="dirPac" #dirPacCtrl="ngModel" required minlength="5" maxlength="200" autocomplete="off" placeholder="Dirección del paciente"
               style="width: 100%; padding: 10px 14px; border: 1px solid #d5dceb; border-radius: 11px; font-size: 14px; background: #f8fafc; color: #07153a;" />
        <app-error-mensaje [control]="dirPacCtrl"></app-error-mensaje>
      </div>

      <div style="margin-top: 14px;">
        <label for="medico" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Médico</label>
        <select id="medico" [(ngModel)]="formAdmision.idMedico"
                style="width: 100%; padding: 10px 14px; border: 1px solid #d5dceb; border-radius: 11px; font-size: 14px; background: #f8fafc; color: #07153a;">
          <option value="">— Seleccionar médico —</option>
          @for (med of medicosDisponibles; track med['idMedico']) {
            <option [ngValue]="med['idMedico']">{{ med['nombreCompleto'] }}</option>
          }
        </select>
        @if (cargandoMedicos) {
          <div style="font-size: 11px; color: #7a86a1; margin-top: 4px;">Cargando médicos...</div>
        }
        @if (errorMedicos) {
          <div style="font-size: 11px; color: #b91c1c; margin-top: 4px;">{{ errorMedicos }}</div>
        }
      </div>

      <div style="margin-top: 14px;">
        <label for="observacion" style="display: block; font-size: 12px; font-weight: 600; color: #54617f; margin-bottom: 6px;">Observación</label>
        <textarea id="observacion" [(ngModel)]="formAdmision.observacion" rows="3" maxlength="500" placeholder="Observación de la admisión"
                  style="width: 100%; padding: 10px 14px; border: 1px solid #d5dceb; border-radius: 11px; font-size: 14px; background: #f8fafc; color: #07153a; resize: vertical; font-family: inherit;"></textarea>
      </div>

      @if (errorAdmision) {
        <div style="margin-top: 14px; background: #fee2e2; border: 1px solid #fca5a5; color: #b91c1c; font-size: 13px; font-weight: 500; padding: 10px 13px; border-radius: 11px;">
          {{ errorAdmision }}
        </div>
      }

      <div style="display: flex; justify-content: flex-end; gap: 10px; margin-top: 22px;">
        <button type="button" (click)="cerrarModalAdmision()"
                style="padding: 10px 20px; border: 1px solid #e0e6f1; border-radius: 11px; background: #fff; font-size: 14px; font-weight: 600; color: #54617f; cursor: pointer;">
          Cancelar
        </button>
        <button type="button" (click)="admitir()" [disabled]="guardando"
                style="padding: 10px 22px; background: #263c7a; color: #fff; border: none; border-radius: 11px; font-size: 14px; font-weight: 600; cursor: pointer;"
                [style.opacity]="guardando ? 0.7 : 1">
          {{ guardando ? 'Registrando...' : 'Registrar admisión' }}
        </button>
      </div>
    </ventana-modal>
  }

  @if (modalFichaId) {
    <app-ficha-admision [idCuentaAtencion]="modalFichaId" (alCerrar)="cerrarFicha()"></app-ficha-admision>
  }

  @if (modalFuaId) {
    <app-sis-fua-report [idCuentaAtencion]="modalFuaId" (alCerrar)="cerrarFua()"></app-sis-fua-report>
  }
</div>
